import { Hero } from "../modeles/hero";
import { Team } from "../modeles/team";

export var TEAM: Team ;
export var OWNED: Hero[] = [];
export const HEROS: Hero[] = [

  {
    id: 1,
    name: 'Alencia',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Green',
    picture: 'assets/alencia.png',
    imprint:0
  },
  {
    id: 2,
    name: 'Ambitious Tywin',
    role: 'Knight',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Light',
    picture: 'assets/ambitious-tywin.png',
    imprint:0
  },
  {
    id: 3,
    name: 'Apocalypse Ravi',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Dark',
    picture: 'assets/apocalypse-ravi.png',
    imprint:0
  },
  {
    id: 4,
    name: 'Arbiter Vildred',
    role: 'Assassin',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Dark',
    picture: 'assets/arbiter-vildred.png',
    imprint:0
  },
  {
    id: 5,
    name: 'Cermia',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Red',
    picture: 'assets/cermia.png',
    imprint:0
  },
  {
    id: 6,
    name: 'Charles',
    role: 'Knight',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Green',
    picture: 'assets/charles.png',
    imprint:0
  },
  {
    id: 7,
    name: 'Dark Corvus',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Dark',
    picture: 'assets/dark-corvus.png',
    imprint:0
  },
  {
    id: 8,
    name: 'Destina',
    role: 'Soul-weaver',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Green',
    picture: 'assets/destina.png',
    imprint:0
  },
  {
    id: 9,
    name: 'Diene',
    role: 'Soul-weaver',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Blue',
    picture: 'assets/diene.png',
    imprint:0
  },
  {
    id: 10,
    name: 'Faithless Lidica',
    role: 'Ranger',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Light',
    picture: 'assets/faithless-lidica.png',
    imprint:0
  },
  {
    id: 11,
    name: 'Fallen Cecilia',
    role: 'Knight',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Dark',
    picture: 'assets/fallen-cecilia.png',
    imprint:0
  },
  {
    id: 12,
    name: 'Kawerik',
    role: 'Mage',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Red',
    picture: 'assets/kawerik.png',
    imprint:0
  },
  {
    id: 13,
    name: 'Lilibet',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Green',
    picture: 'assets/lilibet.png',
    imprint:0
  },
  {
    id: 14,
    name: 'Little Queen Charlotte',
    role: 'Warrior',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Light',
    picture: 'assets/little-queen-charlotte.png',
    imprint:0
  },
  {
    id: 15,
    name: 'Melissa',
    role: 'Mage',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Red',
    picture: 'assets/melissa.png',
    imprint:0
  },
  {
    id: 16,
    name: 'Ruele Of Light',
    role: 'Soul-weaver',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Light',
    picture: 'assets/ruele-of-light.png',
    imprint:0
  },
  {
    id: 17,
    name: 'Seaside Bellona',
    role: 'Ranger',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Blue',
    picture: 'assets/seaside-bellona.png',
    imprint:0
  },
  {
    id: 18,
    name: 'Sez',
    role: 'Assassin',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Blue',
    picture: 'assets/sez.png',
    imprint:0
  },
  {
    id: 19,
    name: 'Tenebria',
    role: 'Mage',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Red',
    picture: 'assets/tenebria.png',
    imprint:0
  },
  {
    id: 20,
    name: 'Zeno',
    role: 'Mage',
    rarity: 5,
    hp: 5769,
    atk: 825,
    def: 599,
    speed: 106,
    element: 'Blue',
    picture: 'assets/zeno.png',
    imprint:0
  }
];
